#!/bin/sh
#
# autogen.sh : regenerate the autotools build system from configure.ac / Makefile.am.
#
# Run this once after a fresh git checkout (or after editing configure.ac or Makefile.am)
# to produce ./configure, Makefile.in, and config.h.in. Released tarballs made with
# `make dist` already ship these generated files, so end users and the Homebrew formula
# do NOT need autotools -- they can run ./configure directly.
#
set -e

# AC_CONFIG_MACRO_DIRS points here; aclocal needs the directory to exist.
mkdir -p m4

# Regenerate the list of bundled example knot files (data/*.vect) that Makefile.am includes,
# so the installed/distributed set can never drift out of sync with the data/ directory.
# This must run before autoreconf, since automake reads the included fragment at that point.
{
	printf '# Generated by autogen.sh from the contents of data/ -- do not edit by hand.\n'
	printf 'dist_pkgdata_DATA ='
	for f in data/*.vect; do
		printf ' \\\n\t%s' "$f"
	done
	printf '\n'
} > data/knotdata.am

autoreconf --install --verbose

echo
echo "Bootstrap complete. Now run:"
echo "  ./configure && make && make check"
