# Makefile.in generated by automake 1.6.3 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#
# This is a starter Automake file for ridgerunner created 3/22/7
#
SHELL = /bin/sh

srcdir = .
top_srcdir = .

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/ridgerunner
pkglibdir = $(libdir)/ridgerunner
pkgincludedir = $(includedir)/ridgerunner
top_builddir = .

ACLOCAL = ${SHELL} /Users/cantarel/ridgerunner/missing --run aclocal-1.6
AUTOCONF = ${SHELL} /Users/cantarel/ridgerunner/missing --run autoconf
AUTOMAKE = ${SHELL} /Users/cantarel/ridgerunner/missing --run automake-1.6
AUTOHEADER = ${SHELL} /Users/cantarel/ridgerunner/missing --run autoheader

am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :

EXEEXT = 
OBJEXT = o
PATH_SEPARATOR = :
AMTAR = ${SHELL} /Users/cantarel/ridgerunner/missing --run tar
AWK = gawk
CC = gcc
CPP = gcc -E
DEPDIR = .deps
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LEX = flex
LEXLIB = -lfl
LEX_OUTPUT_ROOT = lex.yy
LIB_VERSION = 1:0:1
LN_S = ln -s
PACKAGE = ridgerunner
STRIP = 
VERSION = 1.0.1
YACC = bison -y
am__include = include
am__quote = 
install_sh = /Users/cantarel/ridgerunner/install-sh

AM_CFLAGS = -g -finline-functions -Wall

bin_PROGRAMS = ridgerunner

ridgerunner_SOURCES = ./src/display.c ./src/errors.c ./src/linklib_additions.c \
	              ./src/settings.c ./src/dlen.c ./src/ridgerunner_main.c \
                      ./src/stepper.c ./src/dlen.h ./src/eqedge.h ./src/errors.h \
                      ./src/settings.h ./src/stepper.h 


ridgerunner_LDADD = -lplCurve -ltsnnls 


# We include a copy of the knotplot distribution of loose knots for testing.
data_DIST = 0.1.vect 0.2.1.vect 0.3.1.vect 0.4.1.vect 10.1.vect  \
	10.10.vect 10.100.vect 10.101.vect 10.102.vect 10.103.vect  \
	10.104.vect 10.105.vect 10.106.vect 10.107.vect 10.108.vect  \
	10.109.vect 10.11.vect 10.110.vect 10.111.vect 10.112.vect  \
	10.113.vect 10.114.vect 10.115.vect 10.116.vect 10.117.vect  \
	10.118.vect 10.119.vect 10.12.vect 10.120.vect 10.121.vect  \
	10.122.vect 10.123.vect 10.124.vect 10.125.vect 10.126.vect  \
	10.127.vect 10.128.vect 10.129.vect 10.13.vect 10.130.vect  \
	10.131.vect 10.132.vect 10.133.vect 10.134.vect 10.135.vect  \
	10.136.vect 10.137.vect 10.138.vect 10.139.vect 10.14.vect  \
	10.140.vect 10.141.vect 10.142.vect 10.143.vect 10.144.vect  \
	10.145.vect 10.146.vect 10.147.vect 10.148.vect 10.149.vect  \
	10.15.vect 10.150.vect 10.151.vect 10.152.vect 10.153.vect  \
	10.154.vect 10.155.vect 10.156.vect 10.157.vect 10.158.vect  \
	10.159.vect 10.16.vect 10.160.vect 10.161.vect 10.162.vect  \
	10.163.vect 10.164.vect 10.165.vect 10.166.vect 10.17.vect  \
	10.18.vect 10.19.vect 10.2.vect 10.20.vect 10.21.vect  \
	10.22.vect 10.23.vect 10.24.vect 10.25.vect 10.26.vect  \
	10.27.vect 10.28.vect 10.29.vect 10.3.vect 10.30.vect  \
	10.31.vect 10.32.vect 10.33.vect 10.34.vect 10.35.vect  \
	10.36.vect 10.37.vect 10.38.vect 10.39.vect 10.4.vect  \
	10.40.vect 10.41.vect 10.42.vect 10.43.vect 10.44.vect  \
	10.45.vect 10.46.vect 10.47.vect 10.48.vect 10.49.vect  \
	10.5.vect 10.50.vect 10.51.vect 10.52.vect 10.53.vect  \
	10.54.vect 10.55.vect 10.56.vect 10.57.vect 10.58.vect  \
	10.59.vect 10.6.vect 10.60.vect 10.61.vect 10.62.vect  \
	10.63.vect 10.64.vect 10.65.vect 10.66.vect 10.67.vect  \
	10.68.vect 10.69.vect 10.7.vect 10.70.vect 10.71.vect  \
	10.72.vect 10.73.vect 10.74.vect 10.75.vect 10.76.vect  \
	10.77.vect 10.78.vect 10.79.vect 10.8.vect 10.80.vect  \
	10.81.vect 10.82.vect 10.83.vect 10.84.vect 10.85.vect  \
	10.86.vect 10.87.vect 10.88.vect 10.89.vect 10.9.vect  \
	10.90.vect 10.91.vect 10.92.vect 10.93.vect 10.94.vect  \
	10.95.vect 10.96.vect 10.97.vect 10.98.vect 10.99.vect  \
	2.2.1.vect 3.1.vect 4.1.vect 4.2.1.vect 5.1.vect  \
	5.2.1.vect 5.2.vect 6.1.vect 6.2.1.vect 6.2.2.vect  \
	6.2.3.vect 6.2.vect 6.3.1.vect 6.3.2.vect 6.3.3.vect  \
	6.3.vect 7.1.vect 7.2.1.vect 7.2.2.vect 7.2.3.vect  \
	7.2.4.vect 7.2.5.vect 7.2.6.vect 7.2.7.vect 7.2.8.vect  \
	7.2.vect 7.3.1.vect 7.3.vect 7.4.vect 7.5.vect  \
	7.6.vect 7.7.vect 8.1.vect 8.10.vect 8.11.vect  \
	8.12.vect 8.13.vect 8.14.vect 8.15.vect 8.16.vect  \
	8.17.vect 8.18.vect 8.19.vect 8.2.1.vect 8.2.10.vect  \
	8.2.11.vect 8.2.12.vect 8.2.13.vect 8.2.14.vect 8.2.15.vect  \
	8.2.16.vect 8.2.2.vect 8.2.3.vect 8.2.4.vect 8.2.5.vect  \
	8.2.6.vect 8.2.7.vect 8.2.8.vect 8.2.9.vect 8.2.vect  \
	8.20.vect 8.21.vect 8.3.1.vect 8.3.10.vect 8.3.2.vect  \
	8.3.3.vect 8.3.4.vect 8.3.5.vect 8.3.6.vect 8.3.7.vect  \
	8.3.8.vect 8.3.9.vect 8.3.vect 8.4.1.vect 8.4.2.vect  \
	8.4.3.vect 8.4.vect 8.5.vect 8.6.vect 8.7.vect  \
	8.8.vect 8.9.vect 9.1.vect 9.10.vect 9.11.vect  \
	9.12.vect 9.13.vect 9.14.vect 9.15.vect 9.16.vect  \
	9.17.vect 9.18.vect 9.19.vect 9.2.1.vect 9.2.10.vect  \
	9.2.11.vect 9.2.12.vect 9.2.13.vect 9.2.14.vect 9.2.15.vect  \
	9.2.16.vect 9.2.17.vect 9.2.18.vect 9.2.19.vect 9.2.2.vect  \
	9.2.20.vect 9.2.21.vect 9.2.22.vect 9.2.23.vect 9.2.24.vect  \
	9.2.25.vect 9.2.26.vect 9.2.27.vect 9.2.28.vect 9.2.29.vect  \
	9.2.3.vect 9.2.30.vect 9.2.31.vect 9.2.32.vect 9.2.33.vect  \
	9.2.34.vect 9.2.35.vect 9.2.36.vect 9.2.37.vect 9.2.38.vect  \
	9.2.39.vect 9.2.4.vect 9.2.40.vect 9.2.41.vect 9.2.42.vect  \
	9.2.43.vect 9.2.44.vect 9.2.45.vect 9.2.46.vect 9.2.47.vect  \
	9.2.48.vect 9.2.49.vect 9.2.5.vect 9.2.50.vect 9.2.51.vect  \
	9.2.52.vect 9.2.53.vect 9.2.54.vect 9.2.55.vect 9.2.56.vect  \
	9.2.57.vect 9.2.58.vect 9.2.59.vect 9.2.6.vect 9.2.60.vect  \
	9.2.61.vect 9.2.7.vect 9.2.8.vect 9.2.9.vect 9.2.vect  \
	9.20.vect 9.21.vect 9.22.vect 9.23.vect 9.24.vect  \
	9.25.vect 9.26.vect 9.27.vect 9.28.vect 9.29.vect  \
	9.3.1.vect 9.3.10.vect 9.3.11.vect 9.3.12.vect 9.3.13.vect  \
	9.3.14.vect 9.3.15.vect 9.3.16.vect 9.3.17.vect 9.3.18.vect  \
	9.3.19.vect 9.3.2.vect 9.3.20.vect 9.3.21.vect 9.3.3.vect  \
	9.3.4.vect 9.3.5.vect 9.3.6.vect 9.3.7.vect 9.3.8.vect  \
	9.3.9.vect 9.3.vect 9.30.vect 9.31.vect 9.32.vect  \
	9.33.vect 9.34.vect 9.35.vect 9.36.vect 9.37.vect  \
	9.38.vect 9.39.vect 9.4.1.vect 9.4.vect 9.40.vect  \
	9.41.vect 9.42.vect 9.43.vect 9.44.vect 9.45.vect  \
	9.46.vect 9.47.vect 9.48.vect 9.49.vect 9.5.vect  

subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = ridgerunner$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_ridgerunner_OBJECTS = display.$(OBJEXT) errors.$(OBJEXT) \
	linklib_additions.$(OBJEXT) settings.$(OBJEXT) dlen.$(OBJEXT) \
	ridgerunner_main.$(OBJEXT) stepper.$(OBJEXT)
ridgerunner_OBJECTS = $(am_ridgerunner_OBJECTS)
ridgerunner_DEPENDENCIES =
ridgerunner_LDFLAGS =

DEFS = -DHAVE_CONFIG_H
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I.
CPPFLAGS = 
LDFLAGS = 
LIBS = -loctrope -lplCurve -lm 
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
DEP_FILES = ./$(DEPDIR)/display.Po ./$(DEPDIR)/dlen.Po \
	./$(DEPDIR)/errors.Po \
	./$(DEPDIR)/linklib_additions.Po \
	./$(DEPDIR)/ridgerunner_main.Po \
	./$(DEPDIR)/settings.Po ./$(DEPDIR)/stepper.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2
DIST_SOURCES = $(ridgerunner_SOURCES)
DIST_COMMON = README AUTHORS COPYING ChangeLog INSTALL Makefile.am \
	Makefile.in NEWS aclocal.m4 config.h.in configure configure.ac \
	depcomp install-sh missing mkinstalldirs
SOURCES = $(ridgerunner_SOURCES)

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj

am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)

$(top_builddir)/config.status: $(srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck
$(srcdir)/configure:  $(srcdir)/configure.ac $(ACLOCAL_M4) $(CONFIGURE_DEPENDENCIES)
	cd $(srcdir) && $(AUTOCONF)

$(ACLOCAL_M4):  configure.ac 
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h

$(srcdir)/config.h.in:  $(top_srcdir)/configure.ac $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOHEADER)
	touch $(srcdir)/config.h.in

distclean-hdr:
	-rm -f config.h stamp-h1
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
display.$(OBJEXT): ./src/display.c
errors.$(OBJEXT): ./src/errors.c
linklib_additions.$(OBJEXT): ./src/linklib_additions.c
settings.$(OBJEXT): ./src/settings.c
dlen.$(OBJEXT): ./src/dlen.c
ridgerunner_main.$(OBJEXT): ./src/ridgerunner_main.c
stepper.$(OBJEXT): ./src/stepper.c
ridgerunner$(EXEEXT): $(ridgerunner_OBJECTS) $(ridgerunner_DEPENDENCIES) 
	@rm -f ridgerunner$(EXEEXT)
	$(LINK) $(ridgerunner_LDFLAGS) $(ridgerunner_OBJECTS) $(ridgerunner_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/display.Po
include ./$(DEPDIR)/dlen.Po
include ./$(DEPDIR)/errors.Po
include ./$(DEPDIR)/linklib_additions.Po
include ./$(DEPDIR)/ridgerunner_main.Po
include ./$(DEPDIR)/settings.Po
include ./$(DEPDIR)/stepper.Po

distclean-depend:
	-rm -rf ./$(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f '$<' || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`

display.o: ./src/display.c
	source='./src/display.c' object='display.o' libtool=no \
	depfile='$(DEPDIR)/display.Po' tmpdepfile='$(DEPDIR)/display.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o display.o `test -f './src/display.c' || echo '$(srcdir)/'`./src/display.c

display.obj: ./src/display.c
	source='./src/display.c' object='display.obj' libtool=no \
	depfile='$(DEPDIR)/display.Po' tmpdepfile='$(DEPDIR)/display.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o display.obj `cygpath -w ./src/display.c`

errors.o: ./src/errors.c
	source='./src/errors.c' object='errors.o' libtool=no \
	depfile='$(DEPDIR)/errors.Po' tmpdepfile='$(DEPDIR)/errors.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o errors.o `test -f './src/errors.c' || echo '$(srcdir)/'`./src/errors.c

errors.obj: ./src/errors.c
	source='./src/errors.c' object='errors.obj' libtool=no \
	depfile='$(DEPDIR)/errors.Po' tmpdepfile='$(DEPDIR)/errors.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o errors.obj `cygpath -w ./src/errors.c`

linklib_additions.o: ./src/linklib_additions.c
	source='./src/linklib_additions.c' object='linklib_additions.o' libtool=no \
	depfile='$(DEPDIR)/linklib_additions.Po' tmpdepfile='$(DEPDIR)/linklib_additions.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o linklib_additions.o `test -f './src/linklib_additions.c' || echo '$(srcdir)/'`./src/linklib_additions.c

linklib_additions.obj: ./src/linklib_additions.c
	source='./src/linklib_additions.c' object='linklib_additions.obj' libtool=no \
	depfile='$(DEPDIR)/linklib_additions.Po' tmpdepfile='$(DEPDIR)/linklib_additions.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o linklib_additions.obj `cygpath -w ./src/linklib_additions.c`

settings.o: ./src/settings.c
	source='./src/settings.c' object='settings.o' libtool=no \
	depfile='$(DEPDIR)/settings.Po' tmpdepfile='$(DEPDIR)/settings.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o settings.o `test -f './src/settings.c' || echo '$(srcdir)/'`./src/settings.c

settings.obj: ./src/settings.c
	source='./src/settings.c' object='settings.obj' libtool=no \
	depfile='$(DEPDIR)/settings.Po' tmpdepfile='$(DEPDIR)/settings.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o settings.obj `cygpath -w ./src/settings.c`

dlen.o: ./src/dlen.c
	source='./src/dlen.c' object='dlen.o' libtool=no \
	depfile='$(DEPDIR)/dlen.Po' tmpdepfile='$(DEPDIR)/dlen.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o dlen.o `test -f './src/dlen.c' || echo '$(srcdir)/'`./src/dlen.c

dlen.obj: ./src/dlen.c
	source='./src/dlen.c' object='dlen.obj' libtool=no \
	depfile='$(DEPDIR)/dlen.Po' tmpdepfile='$(DEPDIR)/dlen.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o dlen.obj `cygpath -w ./src/dlen.c`

ridgerunner_main.o: ./src/ridgerunner_main.c
	source='./src/ridgerunner_main.c' object='ridgerunner_main.o' libtool=no \
	depfile='$(DEPDIR)/ridgerunner_main.Po' tmpdepfile='$(DEPDIR)/ridgerunner_main.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ridgerunner_main.o `test -f './src/ridgerunner_main.c' || echo '$(srcdir)/'`./src/ridgerunner_main.c

ridgerunner_main.obj: ./src/ridgerunner_main.c
	source='./src/ridgerunner_main.c' object='ridgerunner_main.obj' libtool=no \
	depfile='$(DEPDIR)/ridgerunner_main.Po' tmpdepfile='$(DEPDIR)/ridgerunner_main.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ridgerunner_main.obj `cygpath -w ./src/ridgerunner_main.c`

stepper.o: ./src/stepper.c
	source='./src/stepper.c' object='stepper.o' libtool=no \
	depfile='$(DEPDIR)/stepper.Po' tmpdepfile='$(DEPDIR)/stepper.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o stepper.o `test -f './src/stepper.c' || echo '$(srcdir)/'`./src/stepper.c

stepper.obj: ./src/stepper.c
	source='./src/stepper.c' object='stepper.obj' libtool=no \
	depfile='$(DEPDIR)/stepper.Po' tmpdepfile='$(DEPDIR)/stepper.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o stepper.obj `cygpath -w ./src/stepper.c`
CCDEPMODE = depmode=gcc3
uninstall-info-am:

ETAGS = etags
ETAGSFLAGS =

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$tags$$unique" \
	  || $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = .
distdir = $(PACKAGE)-$(VERSION)

am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }

GZIP_ENV = --best
distcleancheck_listfiles = find . -type f -print

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	@list='$(DISTFILES)'; for file in $$list; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkinstalldirs) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist dist-all: distdir
	$(AMTAR) chof - $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	$(am__remove_distdir)
	GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(AMTAR) xf -
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/=build
	mkdir $(distdir)/=inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/=inst && pwd` \
	  && cd $(distdir)/=build \
	  && ../configure --srcdir=.. --prefix=$$dc_install_base \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && (test `find $$dc_install_base -type f -print | wc -l` -le 1 \
	      || { echo "ERROR: files left after uninstall:" ; \
	           find $$dc_install_base -type f -print ; \
	           exit 1; } >&2 ) \
	  && $(MAKE) $(AM_MAKEFLAGS) dist-gzip \
	  && rm -f $(distdir).tar.gz \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@echo "$(distdir).tar.gz is ready for distribution" | \
	  sed 'h;s/./=/g;p;x;p;x'
distcleancheck: distclean
	if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf autom4te.cache
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic dist dist-all dist-gzip distcheck distclean \
	distclean-compile distclean-depend distclean-generic \
	distclean-hdr distclean-tags distcleancheck distdir dvi dvi-am \
	info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-exec install-exec-am \
	install-info install-info-am install-man install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
