# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#
# This is a starter Automake file for ridgerunner created 3/22/7
#

srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/ridgerunner
pkglibdir = $(libdir)/ridgerunner
pkgincludedir = $(includedir)/ridgerunner
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = powerpc-apple-darwin8.10.0
host_triplet = powerpc-apple-darwin8.10.0
bin_PROGRAMS = src/ridgerunner$(EXEEXT)
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	config.guess config.sub depcomp install-sh missing
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_src_ridgerunner_OBJECTS = errors.$(OBJEXT) dlen.$(OBJEXT) \
	linklib_additions.$(OBJEXT) settings.$(OBJEXT) \
	ridgerunner_main.$(OBJEXT) stepper.$(OBJEXT) display.$(OBJEXT)
src_ridgerunner_OBJECTS = $(am_src_ridgerunner_OBJECTS)
am__DEPENDENCIES_1 =
src_ridgerunner_DEPENDENCIES = $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
am__dirstamp = $(am__leading_dot)dirstamp
DEFAULT_INCLUDES = -I. -I$(srcdir) -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(src_ridgerunner_SOURCES)
DIST_SOURCES = $(src_ridgerunner_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /Users/cantarel/ridgerunner/missing --run aclocal-1.9
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /Users/cantarel/ridgerunner/missing --run tar
AUTOCONF = ${SHELL} /Users/cantarel/ridgerunner/missing --run autoconf
AUTOHEADER = ${SHELL} /Users/cantarel/ridgerunner/missing --run autoheader
AUTOMAKE = ${SHELL} /Users/cantarel/ridgerunner/missing --run automake-1.9
AWK = awk
BLAS_LIBS =  
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g
CPP = gcc -E
CPPFLAGS = 
CYGPATH_W = echo
DARWIN_FALSE = #
DARWIN_TRUE = 
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = g77
FFLAGS = -g -O2
FLIBS = -L/sw/lib/gcc/powerpc-apple-darwin8.10.0/3.4.3 -L/sw/lib/gcc/powerpc-apple-darwin8.10.0/3.4.3/../../.. -lfrtbegin -lg2c -lSystemStubs -lSystem -lmx /usr/lib/gcc/powerpc-apple-darwin8/4.0.1/libgcc.a
GREP = /usr/bin/grep
HAVE_LAPACK_FALSE = #
HAVE_LAPACK_TRUE = 
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LAPACK_LIBS = -framework vecLib
LDFLAGS = 
LIBOBJS = 
LIBS = -loctrope -lplCurve -lm 
LIB_VERSION = 1:0:1
LTLIBOBJS = 
MAKEINFO = ${SHELL} /Users/cantarel/ridgerunner/missing --run makeinfo
OBJEXT = o
PACKAGE = ridgerunner
PACKAGE_BUGREPORT = cantarel@math.uga.edu
PACKAGE_NAME = ridgerunner
PACKAGE_STRING = ridgerunner 1.0.1
PACKAGE_TARNAME = ridgerunner
PACKAGE_VERSION = 1.0.1
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.0.1
ac_ct_CC = gcc
ac_ct_F77 = g77
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = powerpc-apple-darwin8.10.0
build_alias = 
build_cpu = powerpc
build_os = darwin8.10.0
build_vendor = apple
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = powerpc-apple-darwin8.10.0
host_alias = 
host_cpu = powerpc
host_os = darwin8.10.0
host_vendor = apple
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = /Users/cantarel/ridgerunner/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(install_sh) -d
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
AM_CFLAGS = -g -finline-functions -Wall
AM_CPPFLAGS = -I$(srcdir)/src/
src_ridgerunner_SOURCES = src/errors.c \
	src/dlen.c \
	src/linklib_additions.c \
	src/settings.c \
	src/ridgerunner_main.c \
        src/stepper.c \
	src/dlen.h \
	src/errors.h \
	src/display.c \
	src/ridgerunner.h \
	src/portability.h

src_ridgerunner_LDADD = -lncurses -lplCurve -ltsnnls -largtable2 -loctrope $(LAPACK_LIBS) $(BLAS_LIBS) $(LIBS) $(FLIBS)

# We include a copy of the knotplot distribution of loose knots for testing.
data_DIST = 0.1.vect 0.2.1.vect 0.3.1.vect 0.4.1.vect 10.1.vect  \
	10.10.vect 10.100.vect 10.101.vect 10.102.vect 10.103.vect  \
	10.104.vect 10.105.vect 10.106.vect 10.107.vect 10.108.vect  \
	10.109.vect 10.11.vect 10.110.vect 10.111.vect 10.112.vect  \
	10.113.vect 10.114.vect 10.115.vect 10.116.vect 10.117.vect  \
	10.118.vect 10.119.vect 10.12.vect 10.120.vect 10.121.vect  \
	10.122.vect 10.123.vect 10.124.vect 10.125.vect 10.126.vect  \
	10.127.vect 10.128.vect 10.129.vect 10.13.vect 10.130.vect  \
	10.131.vect 10.132.vect 10.133.vect 10.134.vect 10.135.vect  \
	10.136.vect 10.137.vect 10.138.vect 10.139.vect 10.14.vect  \
	10.140.vect 10.141.vect 10.142.vect 10.143.vect 10.144.vect  \
	10.145.vect 10.146.vect 10.147.vect 10.148.vect 10.149.vect  \
	10.15.vect 10.150.vect 10.151.vect 10.152.vect 10.153.vect  \
	10.154.vect 10.155.vect 10.156.vect 10.157.vect 10.158.vect  \
	10.159.vect 10.16.vect 10.160.vect 10.161.vect 10.162.vect  \
	10.163.vect 10.164.vect 10.165.vect 10.166.vect 10.17.vect  \
	10.18.vect 10.19.vect 10.2.vect 10.20.vect 10.21.vect  \
	10.22.vect 10.23.vect 10.24.vect 10.25.vect 10.26.vect  \
	10.27.vect 10.28.vect 10.29.vect 10.3.vect 10.30.vect  \
	10.31.vect 10.32.vect 10.33.vect 10.34.vect 10.35.vect  \
	10.36.vect 10.37.vect 10.38.vect 10.39.vect 10.4.vect  \
	10.40.vect 10.41.vect 10.42.vect 10.43.vect 10.44.vect  \
	10.45.vect 10.46.vect 10.47.vect 10.48.vect 10.49.vect  \
	10.5.vect 10.50.vect 10.51.vect 10.52.vect 10.53.vect  \
	10.54.vect 10.55.vect 10.56.vect 10.57.vect 10.58.vect  \
	10.59.vect 10.6.vect 10.60.vect 10.61.vect 10.62.vect  \
	10.63.vect 10.64.vect 10.65.vect 10.66.vect 10.67.vect  \
	10.68.vect 10.69.vect 10.7.vect 10.70.vect 10.71.vect  \
	10.72.vect 10.73.vect 10.74.vect 10.75.vect 10.76.vect  \
	10.77.vect 10.78.vect 10.79.vect 10.8.vect 10.80.vect  \
	10.81.vect 10.82.vect 10.83.vect 10.84.vect 10.85.vect  \
	10.86.vect 10.87.vect 10.88.vect 10.89.vect 10.9.vect  \
	10.90.vect 10.91.vect 10.92.vect 10.93.vect 10.94.vect  \
	10.95.vect 10.96.vect 10.97.vect 10.98.vect 10.99.vect  \
	2.2.1.vect 3.1.vect 4.1.vect 4.2.1.vect 5.1.vect  \
	5.2.1.vect 5.2.vect 6.1.vect 6.2.1.vect 6.2.2.vect  \
	6.2.3.vect 6.2.vect 6.3.1.vect 6.3.2.vect 6.3.3.vect  \
	6.3.vect 7.1.vect 7.2.1.vect 7.2.2.vect 7.2.3.vect  \
	7.2.4.vect 7.2.5.vect 7.2.6.vect 7.2.7.vect 7.2.8.vect  \
	7.2.vect 7.3.1.vect 7.3.vect 7.4.vect 7.5.vect  \
	7.6.vect 7.7.vect 8.1.vect 8.10.vect 8.11.vect  \
	8.12.vect 8.13.vect 8.14.vect 8.15.vect 8.16.vect  \
	8.17.vect 8.18.vect 8.19.vect 8.2.1.vect 8.2.10.vect  \
	8.2.11.vect 8.2.12.vect 8.2.13.vect 8.2.14.vect 8.2.15.vect  \
	8.2.16.vect 8.2.2.vect 8.2.3.vect 8.2.4.vect 8.2.5.vect  \
	8.2.6.vect 8.2.7.vect 8.2.8.vect 8.2.9.vect 8.2.vect  \
	8.20.vect 8.21.vect 8.3.1.vect 8.3.10.vect 8.3.2.vect  \
	8.3.3.vect 8.3.4.vect 8.3.5.vect 8.3.6.vect 8.3.7.vect  \
	8.3.8.vect 8.3.9.vect 8.3.vect 8.4.1.vect 8.4.2.vect  \
	8.4.3.vect 8.4.vect 8.5.vect 8.6.vect 8.7.vect  \
	8.8.vect 8.9.vect 9.1.vect 9.10.vect 9.11.vect  \
	9.12.vect 9.13.vect 9.14.vect 9.15.vect 9.16.vect  \
	9.17.vect 9.18.vect 9.19.vect 9.2.1.vect 9.2.10.vect  \
	9.2.11.vect 9.2.12.vect 9.2.13.vect 9.2.14.vect 9.2.15.vect  \
	9.2.16.vect 9.2.17.vect 9.2.18.vect 9.2.19.vect 9.2.2.vect  \
	9.2.20.vect 9.2.21.vect 9.2.22.vect 9.2.23.vect 9.2.24.vect  \
	9.2.25.vect 9.2.26.vect 9.2.27.vect 9.2.28.vect 9.2.29.vect  \
	9.2.3.vect 9.2.30.vect 9.2.31.vect 9.2.32.vect 9.2.33.vect  \
	9.2.34.vect 9.2.35.vect 9.2.36.vect 9.2.37.vect 9.2.38.vect  \
	9.2.39.vect 9.2.4.vect 9.2.40.vect 9.2.41.vect 9.2.42.vect  \
	9.2.43.vect 9.2.44.vect 9.2.45.vect 9.2.46.vect 9.2.47.vect  \
	9.2.48.vect 9.2.49.vect 9.2.5.vect 9.2.50.vect 9.2.51.vect  \
	9.2.52.vect 9.2.53.vect 9.2.54.vect 9.2.55.vect 9.2.56.vect  \
	9.2.57.vect 9.2.58.vect 9.2.59.vect 9.2.6.vect 9.2.60.vect  \
	9.2.61.vect 9.2.7.vect 9.2.8.vect 9.2.9.vect 9.2.vect  \
	9.20.vect 9.21.vect 9.22.vect 9.23.vect 9.24.vect  \
	9.25.vect 9.26.vect 9.27.vect 9.28.vect 9.29.vect  \
	9.3.1.vect 9.3.10.vect 9.3.11.vect 9.3.12.vect 9.3.13.vect  \
	9.3.14.vect 9.3.15.vect 9.3.16.vect 9.3.17.vect 9.3.18.vect  \
	9.3.19.vect 9.3.2.vect 9.3.20.vect 9.3.21.vect 9.3.3.vect  \
	9.3.4.vect 9.3.5.vect 9.3.6.vect 9.3.7.vect 9.3.8.vect  \
	9.3.9.vect 9.3.vect 9.30.vect 9.31.vect 9.32.vect  \
	9.33.vect 9.34.vect 9.35.vect 9.36.vect 9.37.vect  \
	9.38.vect 9.39.vect 9.4.1.vect 9.4.vect 9.40.vect  \
	9.41.vect 9.42.vect 9.43.vect 9.44.vect 9.45.vect  \
	9.46.vect 9.47.vect 9.48.vect 9.49.vect 9.5.vect  

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(mkdir_p) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
src/$(am__dirstamp):
	@$(mkdir_p) src
	@: > src/$(am__dirstamp)
src/ridgerunner$(EXEEXT): $(src_ridgerunner_OBJECTS) $(src_ridgerunner_DEPENDENCIES) src/$(am__dirstamp)
	@rm -f src/ridgerunner$(EXEEXT)
	$(LINK) $(src_ridgerunner_LDFLAGS) $(src_ridgerunner_OBJECTS) $(src_ridgerunner_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/display.Po
include ./$(DEPDIR)/dlen.Po
include ./$(DEPDIR)/errors.Po
include ./$(DEPDIR)/linklib_additions.Po
include ./$(DEPDIR)/ridgerunner_main.Po
include ./$(DEPDIR)/settings.Po
include ./$(DEPDIR)/stepper.Po

.c.o:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	if $(COMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`

errors.o: src/errors.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT errors.o -MD -MP -MF "$(DEPDIR)/errors.Tpo" -c -o errors.o `test -f 'src/errors.c' || echo '$(srcdir)/'`src/errors.c; \
	then mv -f "$(DEPDIR)/errors.Tpo" "$(DEPDIR)/errors.Po"; else rm -f "$(DEPDIR)/errors.Tpo"; exit 1; fi
#	source='src/errors.c' object='errors.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o errors.o `test -f 'src/errors.c' || echo '$(srcdir)/'`src/errors.c

errors.obj: src/errors.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT errors.obj -MD -MP -MF "$(DEPDIR)/errors.Tpo" -c -o errors.obj `if test -f 'src/errors.c'; then $(CYGPATH_W) 'src/errors.c'; else $(CYGPATH_W) '$(srcdir)/src/errors.c'; fi`; \
	then mv -f "$(DEPDIR)/errors.Tpo" "$(DEPDIR)/errors.Po"; else rm -f "$(DEPDIR)/errors.Tpo"; exit 1; fi
#	source='src/errors.c' object='errors.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o errors.obj `if test -f 'src/errors.c'; then $(CYGPATH_W) 'src/errors.c'; else $(CYGPATH_W) '$(srcdir)/src/errors.c'; fi`

dlen.o: src/dlen.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT dlen.o -MD -MP -MF "$(DEPDIR)/dlen.Tpo" -c -o dlen.o `test -f 'src/dlen.c' || echo '$(srcdir)/'`src/dlen.c; \
	then mv -f "$(DEPDIR)/dlen.Tpo" "$(DEPDIR)/dlen.Po"; else rm -f "$(DEPDIR)/dlen.Tpo"; exit 1; fi
#	source='src/dlen.c' object='dlen.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o dlen.o `test -f 'src/dlen.c' || echo '$(srcdir)/'`src/dlen.c

dlen.obj: src/dlen.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT dlen.obj -MD -MP -MF "$(DEPDIR)/dlen.Tpo" -c -o dlen.obj `if test -f 'src/dlen.c'; then $(CYGPATH_W) 'src/dlen.c'; else $(CYGPATH_W) '$(srcdir)/src/dlen.c'; fi`; \
	then mv -f "$(DEPDIR)/dlen.Tpo" "$(DEPDIR)/dlen.Po"; else rm -f "$(DEPDIR)/dlen.Tpo"; exit 1; fi
#	source='src/dlen.c' object='dlen.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o dlen.obj `if test -f 'src/dlen.c'; then $(CYGPATH_W) 'src/dlen.c'; else $(CYGPATH_W) '$(srcdir)/src/dlen.c'; fi`

linklib_additions.o: src/linklib_additions.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT linklib_additions.o -MD -MP -MF "$(DEPDIR)/linklib_additions.Tpo" -c -o linklib_additions.o `test -f 'src/linklib_additions.c' || echo '$(srcdir)/'`src/linklib_additions.c; \
	then mv -f "$(DEPDIR)/linklib_additions.Tpo" "$(DEPDIR)/linklib_additions.Po"; else rm -f "$(DEPDIR)/linklib_additions.Tpo"; exit 1; fi
#	source='src/linklib_additions.c' object='linklib_additions.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o linklib_additions.o `test -f 'src/linklib_additions.c' || echo '$(srcdir)/'`src/linklib_additions.c

linklib_additions.obj: src/linklib_additions.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT linklib_additions.obj -MD -MP -MF "$(DEPDIR)/linklib_additions.Tpo" -c -o linklib_additions.obj `if test -f 'src/linklib_additions.c'; then $(CYGPATH_W) 'src/linklib_additions.c'; else $(CYGPATH_W) '$(srcdir)/src/linklib_additions.c'; fi`; \
	then mv -f "$(DEPDIR)/linklib_additions.Tpo" "$(DEPDIR)/linklib_additions.Po"; else rm -f "$(DEPDIR)/linklib_additions.Tpo"; exit 1; fi
#	source='src/linklib_additions.c' object='linklib_additions.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o linklib_additions.obj `if test -f 'src/linklib_additions.c'; then $(CYGPATH_W) 'src/linklib_additions.c'; else $(CYGPATH_W) '$(srcdir)/src/linklib_additions.c'; fi`

settings.o: src/settings.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT settings.o -MD -MP -MF "$(DEPDIR)/settings.Tpo" -c -o settings.o `test -f 'src/settings.c' || echo '$(srcdir)/'`src/settings.c; \
	then mv -f "$(DEPDIR)/settings.Tpo" "$(DEPDIR)/settings.Po"; else rm -f "$(DEPDIR)/settings.Tpo"; exit 1; fi
#	source='src/settings.c' object='settings.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o settings.o `test -f 'src/settings.c' || echo '$(srcdir)/'`src/settings.c

settings.obj: src/settings.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT settings.obj -MD -MP -MF "$(DEPDIR)/settings.Tpo" -c -o settings.obj `if test -f 'src/settings.c'; then $(CYGPATH_W) 'src/settings.c'; else $(CYGPATH_W) '$(srcdir)/src/settings.c'; fi`; \
	then mv -f "$(DEPDIR)/settings.Tpo" "$(DEPDIR)/settings.Po"; else rm -f "$(DEPDIR)/settings.Tpo"; exit 1; fi
#	source='src/settings.c' object='settings.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o settings.obj `if test -f 'src/settings.c'; then $(CYGPATH_W) 'src/settings.c'; else $(CYGPATH_W) '$(srcdir)/src/settings.c'; fi`

ridgerunner_main.o: src/ridgerunner_main.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ridgerunner_main.o -MD -MP -MF "$(DEPDIR)/ridgerunner_main.Tpo" -c -o ridgerunner_main.o `test -f 'src/ridgerunner_main.c' || echo '$(srcdir)/'`src/ridgerunner_main.c; \
	then mv -f "$(DEPDIR)/ridgerunner_main.Tpo" "$(DEPDIR)/ridgerunner_main.Po"; else rm -f "$(DEPDIR)/ridgerunner_main.Tpo"; exit 1; fi
#	source='src/ridgerunner_main.c' object='ridgerunner_main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ridgerunner_main.o `test -f 'src/ridgerunner_main.c' || echo '$(srcdir)/'`src/ridgerunner_main.c

ridgerunner_main.obj: src/ridgerunner_main.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT ridgerunner_main.obj -MD -MP -MF "$(DEPDIR)/ridgerunner_main.Tpo" -c -o ridgerunner_main.obj `if test -f 'src/ridgerunner_main.c'; then $(CYGPATH_W) 'src/ridgerunner_main.c'; else $(CYGPATH_W) '$(srcdir)/src/ridgerunner_main.c'; fi`; \
	then mv -f "$(DEPDIR)/ridgerunner_main.Tpo" "$(DEPDIR)/ridgerunner_main.Po"; else rm -f "$(DEPDIR)/ridgerunner_main.Tpo"; exit 1; fi
#	source='src/ridgerunner_main.c' object='ridgerunner_main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o ridgerunner_main.obj `if test -f 'src/ridgerunner_main.c'; then $(CYGPATH_W) 'src/ridgerunner_main.c'; else $(CYGPATH_W) '$(srcdir)/src/ridgerunner_main.c'; fi`

stepper.o: src/stepper.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT stepper.o -MD -MP -MF "$(DEPDIR)/stepper.Tpo" -c -o stepper.o `test -f 'src/stepper.c' || echo '$(srcdir)/'`src/stepper.c; \
	then mv -f "$(DEPDIR)/stepper.Tpo" "$(DEPDIR)/stepper.Po"; else rm -f "$(DEPDIR)/stepper.Tpo"; exit 1; fi
#	source='src/stepper.c' object='stepper.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o stepper.o `test -f 'src/stepper.c' || echo '$(srcdir)/'`src/stepper.c

stepper.obj: src/stepper.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT stepper.obj -MD -MP -MF "$(DEPDIR)/stepper.Tpo" -c -o stepper.obj `if test -f 'src/stepper.c'; then $(CYGPATH_W) 'src/stepper.c'; else $(CYGPATH_W) '$(srcdir)/src/stepper.c'; fi`; \
	then mv -f "$(DEPDIR)/stepper.Tpo" "$(DEPDIR)/stepper.Po"; else rm -f "$(DEPDIR)/stepper.Tpo"; exit 1; fi
#	source='src/stepper.c' object='stepper.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o stepper.obj `if test -f 'src/stepper.c'; then $(CYGPATH_W) 'src/stepper.c'; else $(CYGPATH_W) '$(srcdir)/src/stepper.c'; fi`

display.o: src/display.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT display.o -MD -MP -MF "$(DEPDIR)/display.Tpo" -c -o display.o `test -f 'src/display.c' || echo '$(srcdir)/'`src/display.c; \
	then mv -f "$(DEPDIR)/display.Tpo" "$(DEPDIR)/display.Po"; else rm -f "$(DEPDIR)/display.Tpo"; exit 1; fi
#	source='src/display.c' object='display.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o display.o `test -f 'src/display.c' || echo '$(srcdir)/'`src/display.c

display.obj: src/display.c
	if $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT display.obj -MD -MP -MF "$(DEPDIR)/display.Tpo" -c -o display.obj `if test -f 'src/display.c'; then $(CYGPATH_W) 'src/display.c'; else $(CYGPATH_W) '$(srcdir)/src/display.c'; fi`; \
	then mv -f "$(DEPDIR)/display.Tpo" "$(DEPDIR)/display.Po"; else rm -f "$(DEPDIR)/display.Tpo"; exit 1; fi
#	source='src/display.c' object='display.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o display.obj `if test -f 'src/display.c'; then $(CYGPATH_W) 'src/display.c'; else $(CYGPATH_W) '$(srcdir)/src/display.c'; fi`
uninstall-info-am:

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-rm -f src/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-shar dist-tarZ dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-exec \
	install-exec-am install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
